
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbtest?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  resources:
    static-locations: classpath:/templates/,classpath:/static/img/

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8888

